### ISSUE TITLE
TypeError: renderToReadableStream is not a function

### ISSUE THREAD

**Issue by arrow2nd** [yondako/yondako#49]
HonoX を Bun + react-renderer で 

```tsx
export default reactRenderer(
  ({ children, title }) => {
    // ~省略~
  },
  {
    stream: true,
  },
);
```

ってすると

```
TypeError: renderToReadableStream is not a function
    at Context.eval (/Users/arrow2nd/workspace/github.com/yondako/yondako/node_modules/@hono/react-renderer/dist/index.js:13:26)
    at async dispatch (/Users/arrow2nd/workspace/github.com/yondako/yondako/node_modules/hono/dist/compose.js:38:19)
    at async handler (/Users/arrow2nd/workspace/github.com/yondako/yondako/node_modules/hono/dist/hono-base.js:101:39)
    at async dispatch (/Users/arrow2nd/workspace/github.com/yondako/yondako/node_modules/hono/dist/compose.js:32:17)
    at async Object.handler (file:///Users/arrow2nd/workspace/github.com/yondako/yondako/node_modules/@hono/auth-js/dist/index.mjs:105:5)
    at async dispatch (/Users/arrow2nd/workspace/github.com/yondako/yondako/node_modules/hono/dist/compose.js:32:17)
    at async handler (/Users/arrow2nd/workspace/github.com/yondako/yondako/node_modules/hono/dist/hono-base.js:101:39)
    at async dispatch (/Users/arrow2nd/workspace/github.com/yondako/yondako/node_modules/hono/dist/compose.js:32:17)
    at async Object.innerMeta [as handler] (/Users/arrow2nd/workspace/github.com/yondako/yondako/node_modules/honox/dist/server/server.js:85:11)
    at async dispatch (/Users/arrow2nd/workspace/github.com/yondako/yondako/node_modules/hono/dist/compose.js:32:17)
```

になる

honojs/middleware の `#627 ` がたぶん同じ症状だけど解決しなかった

**Comment by arrow2nd** [comment]
わからんのでNext.jsにしちゃうか
